/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FavouritesIndexRouteImport } from './routes/favourites/index'
import { Route as ProductIdIndexRouteImport } from './routes/$productId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FavouritesIndexRoute = FavouritesIndexRouteImport.update({
  id: '/favourites/',
  path: '/favourites/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdIndexRoute = ProductIdIndexRouteImport.update({
  id: '/$productId/',
  path: '/$productId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$productId': typeof ProductIdIndexRoute
  '/favourites': typeof FavouritesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$productId': typeof ProductIdIndexRoute
  '/favourites': typeof FavouritesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$productId/': typeof ProductIdIndexRoute
  '/favourites/': typeof FavouritesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$productId' | '/favourites'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$productId' | '/favourites'
  id: '__root__' | '/' | '/$productId/' | '/favourites/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductIdIndexRoute: typeof ProductIdIndexRoute
  FavouritesIndexRoute: typeof FavouritesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favourites/': {
      id: '/favourites/'
      path: '/favourites'
      fullPath: '/favourites'
      preLoaderRoute: typeof FavouritesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$productId/': {
      id: '/$productId/'
      path: '/$productId'
      fullPath: '/$productId'
      preLoaderRoute: typeof ProductIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductIdIndexRoute: ProductIdIndexRoute,
  FavouritesIndexRoute: FavouritesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
